### ISSUE TITLE
有没有可能让tab键成为筛选键 ？

### ISSUE THREAD

**Issue by ghggn** [HowcanoeWang/rime-lua-aux-code#11]
如题 。

**Comment by ghggn** [comment]
已经解决了 

```
patch:
  key_binder:
    bindings:
      - { when: composing, accept: Tab, send: semicolon }
```

感谢作者的项目 感觉得到了新生
